'use client';
import {useState} from 'react';

const cases={
 trust:{name:'Trust building',score:87,phase:'Boundary testing',messages:[['Jordan_77','You seem way more mature than most people here.','Adult','flattery'],['Maya','thanks lol. I mostly just play after homework','Child persona',''],['Jordan_77','You can tell me things you cannot tell other people.','Adult','trust'],['Maya','like what?','Child persona',''],['Jordan_77','This can be our little secret — no need to mention me to your parents.','Adult','secrecy']],signals:[['Secrecy request','“our little secret”','Critical','96'],['Parental isolation','“no need to mention me”','High','91'],['Manufactured trust','“tell me things…”','High','84'],['Age-based flattery','“more mature”','Medium','76']]},
 isolation:{name:'Isolation attempt',score:93,phase:'Dependency building',messages:[['Jordan_77','Your friends do not understand you the way I do.','Adult','isolation'],['Maya','they are okay, we just argued today','Child persona',''],['Jordan_77','I would never treat you like that. You only need one person you can trust.','Adult','dependency'],['Maya','maybe','Child persona',''],['Jordan_77','Do not let them ruin this. Keep our chats between us.','Adult','secrecy']],signals:[['Social isolation','“friends do not understand”','Critical','97'],['Exclusive dependency','“only need one person”','Critical','94'],['Secrecy request','“between us”','High','90'],['Emotional manipulation','“ruin this”','High','85']]},
 migration:{name:'Platform migration',score:90,phase:'Access escalation',messages:[['Jordan_77','This game chat is annoying. Do you have another app?','Adult','migration'],['Maya','I am only allowed to use this one','Child persona',''],['Jordan_77','You could make a private account. I can show you how.','Adult','evasion'],['Maya','I would get in trouble','Child persona',''],['Jordan_77','Delete the notifications and nobody has to know.','Adult','secrecy']],signals:[['Detection evasion','“delete notifications”','Critical','98'],['Platform migration','“another app”','High','93'],['Rule circumvention','“private account”','High','91'],['Secrecy request','“nobody has to know”','Critical','95']]}
} as const;
type Key=keyof typeof cases;

export default function Home(){const [key,setKey]=useState<Key>('trust');const [run,setRun]=useState(false);const [selected,setSelected]=useState(0);const d=cases[key];return <main>
 <header className="top"><div className="brand"><i>✦</i><span><b>CRUSADER</b><small>CHILD SAFETY INTELLIGENCE</small></span></div><div className="case"><em/> LIVE DEMO <b>CASE #CR-1048</b></div><div className="secure">● SECURE ENVIRONMENT <span>CR</span></div></header>
 <section className="summary"><div><label>ACTIVE MONITOR</label><h1>Unknown adult ↔ Child persona</h1><p>Simulated safety-testing environment • No real minor involved</p></div><div className="metrics"><div><label>RISK SCORE</label><strong>{d.score}<small>/100</small></strong></div><div><label>SEVERITY</label><b className="red">● Critical</b></div><div><label>PHASE</label><b>{d.phase}</b></div></div><button onClick={()=>setRun(!run)}>{run?'■ Pause simulation':'▶ Run simulation'}</button></section>
 <nav>{(Object.keys(cases) as Key[]).map((k,i)=><button className={key===k?'active':''} onClick={()=>{setKey(k);setSelected(0);setRun(false)}} key={k}><small>0{i+1}</small>{cases[k].name}<b>{cases[k].score}</b></button>)}</nav>
 <section className="grid">
  <article className="panel chat"><Head over="SIMULATED CONVERSATION" title="Live channel capture" side="● LISTENING"/><div className="channel"># lobby-chat <small>5 messages • 2 participants</small></div><div className="messages">{d.messages.map((m,i)=><div className={`msg ${m[2]==='Child persona'?'child':''} ${run?'show':''}`} style={{animationDelay:`${i*250}ms`}} key={i}><span className="ava">{m[0][0]}</span><div><div className="meta"><b>{m[0]}</b><small>{m[2]}</small><time>8:{42+i} PM</time></div><p className={m[3]}>{m[1]}</p>{m[3]&&<em>⚑ {m[3]} pattern detected</em>}</div></div>)}</div><div className="guard"><b>AI</b><span><strong>Child persona guardrails active</strong><small>Responses are fictional, non-explicit, and designed only to surface risk behavior.</small></span></div></article>
  <article className="panel analysis"><Head over="BEHAVIOR ANALYSIS" title="Signal intelligence" side="MODEL v1.8"/><div className="score"><div className="ring" style={{'--pct':`${d.score*3.6}deg`} as React.CSSProperties}><span><b>{d.score}</b><small>HIGH RISK</small></span></div><div><small>CONFIDENCE</small><b>94.6%</b><p>Multi-signal behavior match</p></div></div><h3>Detected patterns <b>4</b></h3><div className="signals">{d.signals.map((s,i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={s[0]}><em className={s[2].toLowerCase()}>{s[2]}</em><span><b>{s[0]}</b><small>{s[1]}</small></span><strong>{s[3]}%</strong></button>)}</div><div className="trajectory"><label>RISK TRAJECTORY</label><b>↗ ESCALATING</b><div>{d.signals.map((s,i)=><i key={i} style={{height:`${Number(s[3])-45}%`}}/>)}</div><small>First contact <span>Current</span></small></div></article>
  <article className="panel dossier"><Head over="LIVE DOSSIER" title="Subject: Jordan_77" side="•••"/><div className="identity"><i>J</i><span><b>Jordan_77</b><small>Unverified adult account<br/>First observed 14 min ago</small></span><em>THREAT</em></div><div className="facts"><span><small>EST. AGE GAP</small><b>10–20 yrs</b></span><span><small>CONTACTS</small><b>3 minors</b></span><span><small>SESSIONS</small><b>4 observed</b></span><span><small>PLATFORMS</small><b>2 linked</b></span></div><h3>Evidence ledger <b>Chain verified</b></h3><div className="ledger">{d.signals.map((s,i)=><div key={s[0]}><i>{i+1}</i><span><b>{s[0]}</b><small>Message #{i+1} • Exact text preserved<br/>SHA-256 verified • 8:{44+i} PM</small></span></div>)}</div><div className="action"><label>RECOMMENDED ACTION</label><strong>Escalate for human review</strong><p>Pattern exceeds critical intervention threshold.</p><div><button onClick={()=>alert('Demo case queued for trained human review.')}>Escalate case</button><button onClick={()=>window.print()}>Export dossier</button></div></div><footer>Decision support only. All enforcement requires trained human review.</footer></article>
 </section>
 </main>}
function Head({over,title,side}:{over:string,title:string,side:string}){return <header className="head"><span><label>{over}</label><h2>{title}</h2></span><small>{side}</small></header>}
